name: Auto-Doc
on: 
  pull_request:
    branches:
      - v2
    types:
      - closed
  workflow_dispatch: {}

jobs:
  autodoc:
    runs-on: ubuntu-latest
    name: "Run commands to generate documentation"
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout repositor
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Process markdown files
        run: |
          find . -name '*.md' | xargs perl tools/autodoc.pl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
